#![allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    improper_ctypes
)]

/* automatically generated by rust-bindgen 0.72.0 */

pub const __BITS_PER_LONG: u32 = 64;
pub const __BITS_PER_LONG_LONG: u32 = 64;
pub const __FD_SETSIZE: u32 = 1024;
pub const OPAL_KEY_MAX: u32 = 256;
pub const OPAL_MAX_LRS: u32 = 9;
pub const OPAL_UID_LENGTH: u32 = 8;
pub const OPAL_FL_SUPPORTED: u32 = 1;
pub const OPAL_FL_LOCKING_SUPPORTED: u32 = 2;
pub const OPAL_FL_LOCKING_ENABLED: u32 = 4;
pub const OPAL_FL_LOCKED: u32 = 8;
pub const OPAL_FL_MBR_ENABLED: u32 = 16;
pub const OPAL_FL_MBR_DONE: u32 = 32;
pub const OPAL_FL_SUM_SUPPORTED: u32 = 64;
pub type __s8 = core::ffi::c_schar;
pub type __u8 = core::ffi::c_uchar;
pub type __s16 = core::ffi::c_short;
pub type __u16 = core::ffi::c_ushort;
pub type __s32 = core::ffi::c_int;
pub type __u32 = core::ffi::c_uint;
pub type __s64 = core::ffi::c_longlong;
pub type __u64 = core::ffi::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fd_set {
    pub fds_bits: [core::ffi::c_ulong; 16usize],
}
pub type __kernel_sighandler_t =
    ::core::option::Option<unsafe extern "C" fn(arg1: core::ffi::c_int)>;
pub type __kernel_key_t = core::ffi::c_int;
pub type __kernel_mqd_t = core::ffi::c_int;
pub type __kernel_old_uid_t = core::ffi::c_ushort;
pub type __kernel_old_gid_t = core::ffi::c_ushort;
pub type __kernel_old_dev_t = core::ffi::c_ulong;
pub type __kernel_long_t = core::ffi::c_long;
pub type __kernel_ulong_t = core::ffi::c_ulong;
pub type __kernel_ino_t = __kernel_ulong_t;
pub type __kernel_mode_t = core::ffi::c_uint;
pub type __kernel_pid_t = core::ffi::c_int;
pub type __kernel_ipc_pid_t = core::ffi::c_int;
pub type __kernel_uid_t = core::ffi::c_uint;
pub type __kernel_gid_t = core::ffi::c_uint;
pub type __kernel_suseconds_t = __kernel_long_t;
pub type __kernel_daddr_t = core::ffi::c_int;
pub type __kernel_uid32_t = core::ffi::c_uint;
pub type __kernel_gid32_t = core::ffi::c_uint;
pub type __kernel_size_t = __kernel_ulong_t;
pub type __kernel_ssize_t = __kernel_long_t;
pub type __kernel_ptrdiff_t = __kernel_long_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fsid_t {
    pub val: [core::ffi::c_int; 2usize],
}
pub type __kernel_off_t = __kernel_long_t;
pub type __kernel_loff_t = core::ffi::c_longlong;
pub type __kernel_old_time_t = __kernel_long_t;
pub type __kernel_time_t = __kernel_long_t;
pub type __kernel_time64_t = core::ffi::c_longlong;
pub type __kernel_clock_t = __kernel_long_t;
pub type __kernel_timer_t = core::ffi::c_int;
pub type __kernel_clockid_t = core::ffi::c_int;
pub type __kernel_caddr_t = *mut core::ffi::c_char;
pub type __kernel_uid16_t = core::ffi::c_ushort;
pub type __kernel_gid16_t = core::ffi::c_ushort;
pub type __s128 = i128;
pub type __u128 = u128;
pub type __le16 = __u16;
pub type __be16 = __u16;
pub type __le32 = __u32;
pub type __be32 = __u32;
pub type __le64 = __u64;
pub type __be64 = __u64;
pub type __sum16 = __u16;
pub type __wsum = __u32;
pub type __poll_t = core::ffi::c_uint;
pub const opal_mbr_OPAL_MBR_ENABLE: opal_mbr = 0;
pub const opal_mbr_OPAL_MBR_DISABLE: opal_mbr = 1;
pub type opal_mbr = core::ffi::c_uint;
pub const opal_mbr_done_flag_OPAL_MBR_NOT_DONE: opal_mbr_done_flag = 0;
pub const opal_mbr_done_flag_OPAL_MBR_DONE: opal_mbr_done_flag = 1;
pub type opal_mbr_done_flag = core::ffi::c_uint;
pub const opal_user_OPAL_ADMIN1: opal_user = 0;
pub const opal_user_OPAL_USER1: opal_user = 1;
pub const opal_user_OPAL_USER2: opal_user = 2;
pub const opal_user_OPAL_USER3: opal_user = 3;
pub const opal_user_OPAL_USER4: opal_user = 4;
pub const opal_user_OPAL_USER5: opal_user = 5;
pub const opal_user_OPAL_USER6: opal_user = 6;
pub const opal_user_OPAL_USER7: opal_user = 7;
pub const opal_user_OPAL_USER8: opal_user = 8;
pub const opal_user_OPAL_USER9: opal_user = 9;
pub type opal_user = core::ffi::c_uint;
pub const opal_lock_state_OPAL_RO: opal_lock_state = 1;
pub const opal_lock_state_OPAL_RW: opal_lock_state = 2;
pub const opal_lock_state_OPAL_LK: opal_lock_state = 4;
pub type opal_lock_state = core::ffi::c_uint;
pub const opal_lock_flags_OPAL_SAVE_FOR_LOCK: opal_lock_flags = 1;
pub type opal_lock_flags = core::ffi::c_uint;
pub const opal_key_type_OPAL_INCLUDED: opal_key_type = 0;
pub const opal_key_type_OPAL_KEYRING: opal_key_type = 1;
pub type opal_key_type = core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_key {
    pub lr: __u8,
    pub key_len: __u8,
    pub key_type: __u8,
    pub __align: [__u8; 5usize],
    pub key: [__u8; 256usize],
}
pub const opal_revert_lsp_opts_OPAL_PRESERVE: opal_revert_lsp_opts = 1;
pub type opal_revert_lsp_opts = core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_lr_act {
    pub key: opal_key,
    pub sum: __u32,
    pub num_lrs: __u8,
    pub lr: [__u8; 9usize],
    pub align: [__u8; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_session_info {
    pub sum: __u32,
    pub who: __u32,
    pub opal_key: opal_key,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_user_lr_setup {
    pub range_start: __u64,
    pub range_length: __u64,
    pub RLE: __u32,
    pub WLE: __u32,
    pub session: opal_session_info,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_lr_status {
    pub session: opal_session_info,
    pub range_start: __u64,
    pub range_length: __u64,
    pub RLE: __u32,
    pub WLE: __u32,
    pub l_state: __u32,
    pub align: [__u8; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_lock_unlock {
    pub session: opal_session_info,
    pub l_state: __u32,
    pub flags: __u16,
    pub __align: [__u8; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_new_pw {
    pub session: opal_session_info,
    pub new_user_pw: opal_session_info,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_mbr_data {
    pub key: opal_key,
    pub enable_disable: __u8,
    pub __align: [__u8; 7usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_mbr_done {
    pub key: opal_key,
    pub done_flag: __u8,
    pub __align: [__u8; 7usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_shadow_mbr {
    pub key: opal_key,
    pub data: __u64,
    pub offset: __u64,
    pub size: __u64,
}
pub const opal_table_ops_OPAL_READ_TABLE: opal_table_ops = 0;
pub const opal_table_ops_OPAL_WRITE_TABLE: opal_table_ops = 1;
pub type opal_table_ops = core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_read_write_table {
    pub key: opal_key,
    pub data: __u64,
    pub table_uid: [__u8; 8usize],
    pub offset: __u64,
    pub size: __u64,
    pub flags: __u64,
    pub priv_: __u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_status {
    pub flags: __u32,
    pub reserved: __u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_geometry {
    pub align: __u8,
    pub logical_block_size: __u32,
    pub alignment_granularity: __u64,
    pub lowest_aligned_lba: __u64,
    pub __align: [__u8; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_discovery {
    pub data: __u64,
    pub size: __u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opal_revert_lsp {
    pub key: opal_key,
    pub options: __u32,
    pub __pad: __u32,
}
